apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: keepwork-stage-en
spec: 
  rules: 
  - host: stage-en.keepwork.com
    http: 
      paths:
      - path: /
        backend:
          serviceName: keepwork-stage-en
          servicePort: 80
